export type Level = "o-level" | "a-level";

export interface SubjectSummary {
  slug: string;
  name: string;
  code?: string;
  igcseCode?: string;
}

export interface SubjectDetail extends SubjectSummary {
  syllabusCode: string;
  overview: string;
  topics: string[];
  highlights: [string, string, string];
  format: string;
}

export const levelLabels: Record<Level, string> = {
  "o-level": "O Level",
  "a-level": "A Level",
};

export const oLevelSubjects: SubjectSummary[] = [
  { slug: "islamiyat",               name: "Islamiyat",              code: "2058",        igcseCode: "0493"        },
  { slug: "pakistan-studies",        name: "Pakistan Studies",       code: "2059",        igcseCode: "0448"        },
  { slug: "urdu",                    name: "Urdu (Syllabus A & B)",  code: "3247 / 3248", igcseCode: "0539 / 0540" },
  { slug: "english",                 name: "English Language",       code: "1123",        igcseCode: "0500"        },
  { slug: "mathematics",             name: "Mathematics",            code: "4024",        igcseCode: "0580"        },
  { slug: "physics",                 name: "Physics",                code: "5054",        igcseCode: "0625"        },
  { slug: "chemistry",               name: "Chemistry",              code: "5070",        igcseCode: "0620"        },
  { slug: "biology",                 name: "Biology",                code: "5090",        igcseCode: "0610"        },
  { slug: "additional-mathematics",  name: "Additional Mathematics", code: "4037",        igcseCode: "0606"        },
  { slug: "business-studies",        name: "Business Studies",       code: "7115",        igcseCode: "0450"        },
  { slug: "economics",               name: "Economics",              code: "2281",        igcseCode: "0455"        },
  { slug: "computer-science",        name: "Computer Science",       code: "2210",        igcseCode: "0478"        },
  { slug: "environmental-management",name: "Environmental Management",code: "5014",       igcseCode: "0680"        },
  { slug: "sociology",               name: "Sociology",              code: "2251",        igcseCode: "0495"        },
  { slug: "accounting",              name: "Accounting",             code: "7707",        igcseCode: "0452"        },
];

export const aLevelSubjects: SubjectSummary[] = [
  { slug: "mathematics",          name: "Mathematics",        code: "9709" },
  { slug: "further-mathematics",  name: "Further Mathematics",code: "9231" },
  { slug: "physics",              name: "Physics",            code: "9702" },
  { slug: "computer-science",     name: "Computer Science",   code: "9618" },
  { slug: "chemistry",            name: "Chemistry",          code: "9701" },
  { slug: "biology",              name: "Biology",            code: "9700" },
  { slug: "business-studies",     name: "Business",           code: "9609" },
  { slug: "economics",            name: "Economics",          code: "9708" },
  { slug: "accounting",           name: "Accounting",         code: "9706" },
  { slug: "english",              name: "English Language",   code: "9093" },
  { slug: "psychology",           name: "Psychology",         code: "9698" },
  { slug: "sociology",            name: "Sociology",          code: "9699" },
];

export const subjectsByLevel: Record<Level, SubjectSummary[]> = {
  "o-level": oLevelSubjects,
  "a-level": aLevelSubjects,
};

const oLevelDetails: Record<string, SubjectDetail> = {
  islamiyat: {
    slug: "islamiyat",
    name: "Islamiyat",
    code: "2058",
    igcseCode: "0493",
    syllabusCode: "2058 / IGCSE 0493",
    overview:
      "Forte Institute's O Level Islamiyat course builds a deep, exam-ready understanding of Islamic teachings, history and jurisprudence as tested by Cambridge. Every session is structured around source-based questions and essay frameworks — the exact skills that convert knowledge into A* marks.",
    topics: [
      "Life of the Prophet Muhammad (ﷺ)",
      "The Quran — Revelation, Compilation & Authority",
      "Hadith — Types, Transmission & Importance",
      "The Five Pillars of Islam",
      "Islamic Jurisprudence (Fiqh) Foundations",
      "The Rightly-Guided Caliphs",
      "Spread of Islam & Early Muslim Civilisation",
      "Islamic Ethics & Social Teachings",
      "Source Interpretation Technique",
      "Essay Writing for Paper 2",
      "Past Paper Practice — Paper 1 & 2",
    ],
    highlights: [
      "Source-based questions mastered — the highest-yield Paper 1 skill",
      "Structured essay frameworks that score full marks on every prompt",
      "Complete coverage of both Paper 1 and Paper 2 topics",
    ],
    format: "In Class & Online · Pakistan",
  },
  "pakistan-studies": {
    slug: "pakistan-studies",
    name: "Pakistan Studies",
    code: "2059",
    igcseCode: "0448",
    syllabusCode: "2059 / IGCSE 0448",
    overview:
      "Our O Level Pakistan Studies classes cover the full Cambridge syllabus — Geography, History and the political narrative — with a focus on the data-response and essay question types that define the exam. Students leave every session knowing exactly how to structure an answer the examiner will reward.",
    topics: [
      "Physical Geography — Relief, Drainage & Climate",
      "Natural Resources, Agriculture & Land Use",
      "Industry, Trade & Economic Development",
      "Population — Distribution, Growth & Migration",
      "Urbanisation & Environmental Challenges",
      "Independence Movement & Partition 1947",
      "Constitutional & Political Development",
      "Pakistan's History since Independence",
      "Map Work & Data Response Technique",
      "Essay Technique for Paper 2",
      "Past Paper Practice — Paper 1 & 2",
    ],
    highlights: [
      "Map-work and data-response questions broken down step by step",
      "Political and economic history taught as connected narratives, not isolated facts",
      "Essay structures for every question type in Paper 2",
    ],
    format: "In Class & Online · Pakistan",
  },
  urdu: {
    slug: "urdu",
    name: "Urdu (Syllabus A & B)",
    code: "3247 / 3248",
    igcseCode: "0539 / 0540",
    syllabusCode: "3247 / 3248 · IGCSE 0539 / 0540",
    overview:
      "Forte's O Level Urdu classes cover both Syllabus A and Syllabus B, building the grammar, composition and comprehension skills Cambridge examiners expect. From mazmoon nigari to translation, every class follows the exact format of the papers — so exam day feels like practice.",
    topics: [
      "Grammar & Vocabulary (Qawa'id)",
      "Comprehension (Fehm-e-Ibarat)",
      "Essay Writing (Mazmoon Nigari)",
      "Formal Letter & Application Writing",
      "Story Writing (Kahani Nigari)",
      "Paragraph & Summary Writing",
      "Translation — Urdu ↔ English",
      "Prose & Poetry Appreciation",
      "Directed Writing (Syllabus B)",
      "Exam Timing & Mark Scheme Technique",
    ],
    highlights: [
      "Essay and composition frameworks taught for every question type",
      "Full coverage of both Syllabus A (3247) and Syllabus B (3248)",
      "Translation skills built systematically — both directions",
    ],
    format: "In Class & Online · Pakistan",
  },
  english: {
    slug: "english",
    name: "English Language",
    code: "1123",
    igcseCode: "0500",
    syllabusCode: "1123 / IGCSE 0500",
    overview:
      "O Level English Language at Forte is built around the two skills Cambridge tests hardest: comprehension under pressure and quality writing. Sessions follow the real paper structure — inference questions, summary writing, directed writing and extended composition — so students know exactly where marks come from and how to get them.",
    topics: [
      "Reading Comprehension — Explicit & Implicit Detail",
      "Inference & Writer's Effect (Paper 2)",
      "Summary Writing — Selection & Paraphrasing",
      "Directed Writing — Letters, Reports, Articles & Speeches",
      "Narrative & Descriptive Writing",
      "Argumentative & Discursive Essays",
      "Language & Vocabulary in Context",
      "Note-Making & Synthesis",
      "Proofreading & Editing",
      "Exam Timing & Mark Scheme Technique",
    ],
    highlights: [
      "Comprehension technique that targets every mark type — explicit, implicit and language effect",
      "Directed writing frameworks for letters, reports, articles and speeches",
      "Timed practice that builds speed and composition quality simultaneously",
    ],
    format: "In Class & Online · Pakistan",
  },
  mathematics: {
    slug: "mathematics",
    name: "Mathematics",
    code: "4024",
    igcseCode: "0580",
    syllabusCode: "4024 / IGCSE 0580",
    overview:
      "Forte's O Level Mathematics classes strip away confusion and build genuine problem-solving ability. From number theory to trigonometry to statistics, every topic is taught conceptually first — then cemented through Cambridge-style past paper questions so students can handle any variant the examiner writes.",
    topics: [
      "Number — Integers, Fractions, Decimals & Percentages",
      "Algebra — Expressions, Equations & Inequalities",
      "Functions & Sequences",
      "Geometry — Lines, Angles & Polygons",
      "Circles — Theorems & Calculations",
      "Mensuration — Perimeter, Area & Volume",
      "Trigonometry — Right Triangles, Sine & Cosine Rules",
      "Statistics — Averages, Frequency Tables & Histograms",
      "Probability",
      "Vectors & Transformations",
      "Coordinate Geometry",
      "Matrices",
    ],
    highlights: [
      "Concepts taught from first principles — no formulae without understanding",
      "Every topic reinforced with Cambridge past-paper questions",
      "Both Paper 1 (non-calculator) and Paper 2 strategies covered",
    ],
    format: "In Class & Online · Pakistan",
  },
  physics: {
    slug: "physics",
    name: "Physics",
    code: "5054",
    igcseCode: "0625",
    syllabusCode: "5054 / IGCSE 0625",
    overview:
      "O Level Physics at Forte is taught with a strong emphasis on understanding — not memorisation. Sessions cover the full Cambridge syllabus from mechanics to nuclear physics, with dedicated time for experimental skills and the structured written responses that earn marks in Section B.",
    topics: [
      "Measurement & Units",
      "Forces & Motion — Kinematics & Dynamics",
      "Mass, Weight, Density & Pressure",
      "Thermal Physics — Heat Transfer & Thermometry",
      "Waves — Light, Sound & Electromagnetic Spectrum",
      "Electricity — Circuits, Components & Calculations",
      "Magnetism & Electromagnetism",
      "Nuclear Physics — Radioactivity & Half-life",
      "Practical Skills — Experiment Design & Data Analysis",
      "Section B Structured Questions Technique",
    ],
    highlights: [
      "Conceptual explanations before calculations — understanding drives marks",
      "Section B written-response technique taught explicitly",
      "Practical skills and experiment analysis covered fully",
    ],
    format: "In Class & Online · Pakistan",
  },
  chemistry: {
    slug: "chemistry",
    name: "Chemistry",
    code: "5070",
    igcseCode: "0620",
    syllabusCode: "5070 / IGCSE 0620",
    overview:
      "Forte's O Level Chemistry course covers the full Cambridge syllabus — from atomic structure and bonding to organic chemistry — with a focus on the reasoning skills the examiner rewards. Every difficult concept is taught with clear mechanistic explanations, not rote facts, so students can answer unseen questions confidently.",
    topics: [
      "States of Matter & Kinetic Theory",
      "Atomic Structure & Chemical Bonding",
      "Formulae, Equations & Stoichiometry",
      "Acids, Bases & Salts",
      "Electrolysis",
      "Energetics — Exothermic & Endothermic Reactions",
      "Rates of Reaction & Catalysis",
      "Organic Chemistry — Alkanes, Alkenes, Alcohols & Polymers",
      "Periodic Table & Group Properties",
      "Metals, Reactivity Series & Extraction",
      "Environmental Chemistry",
      "Practical & Experimental Chemistry",
    ],
    highlights: [
      "Mechanisms and explanations — not just definitions to memorise",
      "Organic chemistry taught as a connected system, not isolated reactions",
      "Practical question technique and data analysis built in",
    ],
    format: "In Class & Online · Pakistan",
  },
  biology: {
    slug: "biology",
    name: "Biology",
    code: "5090",
    igcseCode: "0610",
    syllabusCode: "5090 / IGCSE 0610",
    overview:
      "O Level Biology at Forte builds the understanding and precision that Cambridge Biology demands. From cell biology to genetics, sessions focus on the exact command words — describe, explain, suggest — that determine whether a technically correct answer scores marks or doesn't.",
    topics: [
      "Cell Structure & Function",
      "Movement In & Out of Cells — Diffusion, Osmosis & Active Transport",
      "Biological Molecules — Carbohydrates, Proteins & Lipids",
      "Enzymes — Action, Factors & Inhibition",
      "Nutrition in Humans & Plants",
      "Transport in Humans — Blood, Heart & Blood Vessels",
      "Respiration & Gas Exchange",
      "Excretion — Kidneys & Osmoregulation",
      "Coordination — Nervous & Hormonal Systems",
      "Reproduction — Sexual & Asexual",
      "Genetics — Inheritance & Genetic Diagrams",
      "Ecology & the Environment",
    ],
    highlights: [
      "Command-word technique taught explicitly — describe, explain and suggest all handled differently",
      "Diagram labelling and process explanation drilled systematically",
      "Genetics diagrams and inheritance problems practised to full confidence",
    ],
    format: "In Class & Online · Pakistan",
  },
  "additional-mathematics": {
    slug: "additional-mathematics",
    name: "Additional Mathematics",
    code: "4037",
    igcseCode: "0606",
    syllabusCode: "4037 / IGCSE 0606",
    overview:
      "Additional Mathematics at Forte bridges O Level and A Level thinking. Sessions cover the full Cambridge 4037 syllabus — calculus, trigonometry, permutations and more — taught with rigour and conceptual depth so students are genuinely prepared for both the exam and the transition to A Level Mathematics.",
    topics: [
      "Functions — Domain, Range, Inverse & Composite",
      "Simultaneous Equations & Polynomials",
      "Quadratic Functions & Inequalities",
      "Indices, Surds & Logarithms",
      "Trigonometry — Identities, Equations & Graphs",
      "Permutations & Combinations",
      "Series — Arithmetic & Geometric",
      "Differentiation — Rules & Applications",
      "Integration — Definite & Indefinite",
      "Kinematics & Vectors in 2D",
    ],
    highlights: [
      "Calculus concepts built carefully — derivatives and integrals understood, not just applied",
      "Trigonometric identities mastered through structured proof practice",
      "A Level Mathematics preparation built into every topic",
    ],
    format: "In Class & Online · Pakistan",
  },
  "business-studies": {
    slug: "business-studies",
    name: "Business Studies",
    code: "7115",
    igcseCode: "0450",
    syllabusCode: "7115 / IGCSE 0450",
    overview:
      "Forte's O Level Business Studies classes teach students to think like analysts, not just recall theory. Cambridge Business rewards structured evaluation — every session builds the skill of framing a business problem, applying relevant concepts, and reaching a justified conclusion that earns the top mark band.",
    topics: [
      "The Purpose & Nature of Business Activity",
      "Types of Business Organisation",
      "Business Finance — Sources, Costs, Revenue & Profit",
      "Marketing — The 4Ps & Market Research",
      "Production & Operations Management",
      "Human Resources — Motivation, Recruitment & Organisation",
      "Business Communication",
      "External Influences — Government, Economy & Environment",
      "Business Growth & Strategy",
      "Case Study & Data Response Technique",
    ],
    highlights: [
      "Evaluation skill explicitly taught — the difference between a B and an A*",
      "Case study technique developed through structured practice on real scenarios",
      "Every theory unit linked to real business examples from Pakistan and globally",
    ],
    format: "In Class & Online · Pakistan",
  },
  economics: {
    slug: "economics",
    name: "Economics",
    code: "2281",
    igcseCode: "0455",
    syllabusCode: "2281 / IGCSE 0455",
    overview:
      "O Level Economics at Forte develops both conceptual understanding and the analytical writing Cambridge rewards. From the price mechanism to macroeconomic policy, sessions teach students how to build an economic argument — with diagrams, evidence and a structured conclusion — not just recite definitions.",
    topics: [
      "Basic Economic Problem — Scarcity, Choice & Opportunity Cost",
      "Supply, Demand & Price Mechanism",
      "Elasticity — PED, PES, YED & CED",
      "Market Failure & Government Intervention",
      "Macroeconomic Objectives — GDP, Inflation & Unemployment",
      "Government Policy — Fiscal, Monetary & Supply-Side",
      "International Trade & Globalisation",
      "Balance of Payments & Exchange Rates",
      "Development Economics & Living Standards",
      "Diagram Technique for Economic Analysis",
    ],
    highlights: [
      "Economic diagrams taught correctly — the biggest mark source students miss",
      "Extended writing technique developed for every major question type",
      "Real-world examples from Pakistan's economy used throughout",
    ],
    format: "In Class & Online · Pakistan",
  },
  "computer-science": {
    slug: "computer-science",
    name: "Computer Science",
    code: "2210",
    igcseCode: "0478",
    syllabusCode: "2210 / IGCSE 0478",
    overview:
      "Forte's O Level Computer Science classes build genuine computational thinking — from binary representation to algorithm design to programming. Cambridge CS is both theoretical and practical; every session balances conceptual understanding with pseudocode and logic work so students can handle Paper 1 and Paper 2 with equal confidence.",
    topics: [
      "Data Representation — Binary, Hexadecimal, Text & Images",
      "Computer Architecture — CPU, Memory & Storage",
      "Input & Output Devices",
      "Networking — Topologies, Protocols & the Internet",
      "Cybersecurity & Data Protection",
      "Algorithm Design & Pseudocode",
      "Programming Concepts — Variables, Selection, Loops & Procedures",
      "Data Structures — Arrays & Records",
      "Database Concepts & SQL",
      "Boolean Logic & Logic Gates",
      "System Software & Software Development Lifecycle",
    ],
    highlights: [
      "Pseudocode written to Cambridge standard — the highest-mark skill in Paper 2",
      "Logic gates and Boolean expressions practised to exam confidence",
      "Networking and security covered at the depth Cambridge tests",
    ],
    format: "In Class & Online · Pakistan",
  },
  "environmental-management": {
    slug: "environmental-management",
    name: "Environmental Management",
    code: "5014",
    igcseCode: "0680",
    syllabusCode: "5014 / IGCSE 0680",
    overview:
      "O Level Environmental Management at Forte covers the Cambridge syllabus across all four spheres — lithosphere, atmosphere, hydrosphere and biosphere — with clear connections between human activity and environmental consequence. Data interpretation and case study response are practised in every session.",
    topics: [
      "Lithosphere — Rock Types, Soils & Plate Tectonics",
      "Atmosphere — Weather, Climate & Climate Change",
      "Hydrosphere — Water Cycle & Water Management",
      "Biosphere — Ecosystems, Biodiversity & Deforestation",
      "Human Population — Growth, Migration & Urbanisation",
      "Food & Agriculture — Sustainable Practices",
      "Energy — Fossil Fuels, Renewables & Nuclear",
      "Industrial Development & Pollution",
      "Environmental Management Strategies",
      "Data Interpretation & Case Study Technique",
    ],
    highlights: [
      "All four Cambridge spheres taught with real case studies",
      "Data response questions practised with past paper material",
      "Management strategies evaluated — not just described",
    ],
    format: "In Class & Online · Pakistan",
  },
  sociology: {
    slug: "sociology",
    name: "Sociology",
    code: "2251",
    igcseCode: "0495",
    syllabusCode: "2251 / IGCSE 0495",
    overview:
      "Forte's O Level Sociology course builds both the sociological knowledge and the structured argument Cambridge expects. From socialisation and identity to crime and the media, students learn to apply theoretical perspectives and research evidence to any question — the skill that separates A* answers from average ones.",
    topics: [
      "Socialisation, Culture — Norms, Values & Roles",
      "Social Stratification — Class, Gender, Ethnicity & Age",
      "The Family — Types, Functions & Social Change",
      "Education — Role, Inequality & Achievement",
      "Crime & Deviance — Theories & Statistics",
      "Religion & Belief Systems",
      "Media & Social Influence",
      "Research Methods — Quantitative & Qualitative",
      "Applying Sociological Theory",
      "Extended Writing & Essay Technique",
    ],
    highlights: [
      "Sociological perspectives taught as analytical tools, not just content to recall",
      "Research methods section covered fully — a consistent mark source",
      "Essay structure built around the Cambridge mark scheme",
    ],
    format: "In Class & Online · Pakistan",
  },
  accounting: {
    slug: "accounting",
    name: "Accounting",
    code: "7707",
    igcseCode: "0452",
    syllabusCode: "7707 / IGCSE 0452",
    overview:
      "O Level Accounting at Forte is taught with precision and clarity — from the fundamentals of double-entry bookkeeping through to financial statement preparation and analysis. Sessions follow the exact Forte approach: understand the principle, apply it correctly, then practise on Cambridge past papers until it's automatic.",
    topics: [
      "Double-Entry Bookkeeping & the Accounting Equation",
      "Source Documents & Books of Prime Entry",
      "The General Ledger & Trial Balance",
      "Income Statement Preparation",
      "Balance Sheet (Statement of Financial Position)",
      "Adjustments — Accruals, Prepayments & Depreciation",
      "Control Accounts & Bank Reconciliation",
      "Partnership Accounts",
      "Manufacturing Accounts",
      "Interpretation of Financial Statements",
      "Incomplete Records",
    ],
    highlights: [
      "Double-entry mastered properly — built from first principles",
      "Financial statements prepared to Cambridge format",
      "Adjustments and incomplete records — the topics most students drop marks on",
    ],
    format: "In Class & Online · Pakistan",
  },
};

const aLevelDetails: Record<string, SubjectDetail> = {
  mathematics: {
    slug: "mathematics",
    name: "Mathematics",
    code: "9709",
    syllabusCode: "9709",
    overview:
      "Forte's A Level Mathematics programme covers the full Cambridge 9709 syllabus — Pure, Mechanics and Statistics — with a rigour that builds genuine mathematical ability. Every concept is understood before it's applied, and every topic is reinforced through Cambridge past paper questions so students can handle the full range of exam scenarios.",
    topics: [
      "Pure 1 — Functions, Coordinate Geometry & Trigonometry",
      "Pure 1 — Series, Differentiation & Integration",
      "Pure 2 — Algebra, Logarithms & Differential Equations",
      "Pure 3 — Complex Numbers, Vectors & Further Calculus",
      "Mechanics — Kinematics, Forces & Newton's Laws",
      "Mechanics — Work, Energy, Power & Circular Motion",
      "Statistics — Permutations, Combinations & Probability",
      "Statistics — Probability Distributions — Binomial & Normal",
      "Statistics — Hypothesis Testing",
      "Statistics — Correlation & Regression",
    ],
    highlights: [
      "All three components covered — Pure, Mechanics and Statistics",
      "Proof and explanation required for every technique — not just the answer",
      "Past paper question banks used across every topic",
    ],
    format: "In Class & Online · Pakistan",
  },
  "further-mathematics": {
    slug: "further-mathematics",
    name: "Further Mathematics",
    code: "9231",
    syllabusCode: "9231",
    overview:
      "A Level Further Mathematics at Forte demands and develops the highest level of mathematical thinking. Sessions cover the advanced pure, statistics and mechanics content of Cambridge 9231, taught by tutors who understand both the syllabus depth and the exam strategy needed to score at the top.",
    topics: [
      "Roots of Polynomials & Complex Numbers",
      "Matrices & Linear Transformations",
      "Further Vectors & 3D Geometry",
      "Differential Equations — Second Order & Integrating Factors",
      "Maclaurin's Series & Approximations",
      "Proof by Induction",
      "Further Statistics — Probability Generating Functions",
      "Further Statistics — Hypothesis Testing & Distributions",
      "Further Mechanics — Momentum & Impulse",
      "Further Mechanics — Simple Harmonic Motion",
    ],
    highlights: [
      "Advanced pure content taught with full rigour — proof required, not just calculation",
      "Both the Statistics and Mechanics elective routes covered",
      "Designed for students targeting top universities with Further Maths requirements",
    ],
    format: "In Class & Online · Pakistan",
  },
  physics: {
    slug: "physics",
    name: "Physics",
    code: "9702",
    syllabusCode: "9702",
    overview:
      "A Level Physics at Forte builds the analytical rigour that Cambridge 9702 demands. From quantum mechanics to circular motion to electromagnetic induction, sessions focus on deep understanding, mathematical precision and the structured extended responses that earn top marks in Section B of the written papers.",
    topics: [
      "Measurements, Uncertainties & SI Units",
      "Kinematics, Dynamics & Newton's Laws in 2D",
      "Forces, Momentum, Energy & Power",
      "Circular Motion & Gravitational Fields",
      "Oscillations & Simple Harmonic Motion",
      "Electric Fields, Capacitors & Capacitance",
      "Magnetic Fields & Electromagnetic Induction",
      "Thermal Physics — Internal Energy & Gas Laws",
      "Waves — Superposition, Diffraction & Interference",
      "Quantum Physics — Photoelectric Effect & Energy Levels",
      "Nuclear Physics — Radioactivity, Fission & Fusion",
    ],
    highlights: [
      "Mathematical treatment of every topic — no hand-waving explanations",
      "Extended response technique for Section B built explicitly",
      "Practical skills and data analysis for Paper 3 fully covered",
    ],
    format: "In Class & Online · Pakistan",
  },
  "computer-science": {
    slug: "computer-science",
    name: "Computer Science",
    code: "9618",
    syllabusCode: "9618",
    overview:
      "A Level Computer Science at Forte covers the full Cambridge 9618 syllabus — from processor architecture and networking to OOP, databases and AI — with a programming practice strand running through every session. Students leave with the theoretical grounding and practical coding confidence the exam requires.",
    topics: [
      "Information Representation & Data Structures",
      "Computer Architecture & Processor Design",
      "Communication, Networking & the Internet",
      "Hardware, Virtual Machines & Operating Systems",
      "Privacy, Security & Data Legislation",
      "Algorithm Design — Sorting, Searching & Big-O Notation",
      "OOP — Classes, Inheritance & Polymorphism",
      "Functional & Declarative Programming Paradigms",
      "Databases — Relational Algebra, SQL & Normalisation",
      "Software Development — Testing, Validation & SDLC",
      "AI, Expert Systems & Machine Learning Concepts",
    ],
    highlights: [
      "Pseudocode and programming written to Cambridge standard throughout",
      "OOP taught in depth — the most complex and highest-mark area of the syllabus",
      "Algorithm complexity and Big-O reasoning covered rigorously",
    ],
    format: "In Class & Online · Pakistan",
  },
  chemistry: {
    slug: "chemistry",
    name: "Chemistry",
    code: "9701",
    syllabusCode: "9701",
    overview:
      "A Level Chemistry at Forte is taught at the depth Cambridge 9701 requires — mechanisms, energetics, equilibria and spectroscopy all covered with conceptual rigour. Every session builds the reasoning skills to tackle the extended questions in Paper 4, where most marks are won or lost.",
    topics: [
      "Atomic Structure & Mass Spectrometry",
      "Chemical Bonding & Molecular Structure",
      "Energetics — Hess's Law, Born-Haber & Lattice Energy",
      "Kinetics — Rate Equations & Activation Energy",
      "Equilibrium — Kp, Kc & Le Chatelier's Principle",
      "Electrochemistry — Electrode Potentials & Electrolysis",
      "Organic Chemistry — Mechanisms & Functional Groups",
      "Spectroscopy — IR, Mass Spec & NMR",
      "Nitrogen Chemistry & Polymers",
      "Transition Metals & Coordination Chemistry",
      "Planning & Evaluating Practical Experiments",
    ],
    highlights: [
      "Mechanisms drawn and explained correctly — the biggest A Level Chemistry mark source",
      "Paper 4 planning and evaluation questions practised with structured frameworks",
      "Spectroscopy taught as an interpretive skill, not memory work",
    ],
    format: "In Class & Online · Pakistan",
  },
  biology: {
    slug: "biology",
    name: "Biology",
    code: "9700",
    syllabusCode: "9700",
    overview:
      "A Level Biology at Forte covers the full Cambridge 9700 syllabus with the precision the subject demands. From cell signalling to gene expression to ecology, sessions build both the factual depth and the evaluation skills needed to access the top mark bands across all four papers.",
    topics: [
      "Cell & Nuclear Division — Mitosis, Meiosis & the Cell Cycle",
      "Biological Molecules & Enzyme Action",
      "Transport in Plants — Xylem, Phloem & Translocation",
      "Transport in Animals — Heart, Blood & Haemoglobin",
      "Gas Exchange & Digestion",
      "Neuronal Communication & Hormonal Control",
      "Immunity & Disease",
      "Homeostasis — Osmoregulation & Temperature Control",
      "Gene Expression — DNA Replication, Transcription & Translation",
      "Genetics — Inheritance, Gene Mutation & Evolution",
      "Ecology — Populations, Energy Flow & Conservation",
      "Biotechnology & Recombinant DNA Technology",
    ],
    highlights: [
      "Molecular biology taught with mechanistic precision — transcription, translation and gene regulation",
      "Evaluation questions practised — the most demanding question type in A Level Biology",
      "All four papers covered including the planning and analysis practical paper",
    ],
    format: "In Class & Online · Pakistan",
  },
  "business-studies": {
    slug: "business-studies",
    name: "Business",
    code: "9609",
    syllabusCode: "9609",
    overview:
      "A Level Business at Forte develops the strategic thinking and structured evaluation Cambridge 9609 rewards. From investment appraisal to corporate governance, every session builds the skill of constructing a justified business argument — not just presenting theory — so students can access the highest mark bands.",
    topics: [
      "Business Objectives, Stakeholders & Corporate Governance",
      "Human Resources — Leadership, Motivation & Organisational Design",
      "Operations Management — Capacity, Quality & Lean Production",
      "Marketing — Strategy, Segmentation, Targeting & Research",
      "Finance — Investment Appraisal (Payback, ARR & NPV)",
      "Finance — Budgets, Variance Analysis & Ratio Analysis",
      "Business Growth — Internal, External & Globalisation",
      "Strategic Management — Porter's Five Forces & SWOT",
      "Change Management",
      "International Business & Global Strategy",
    ],
    highlights: [
      "Evaluation explicitly taught — every essay session builds justified conclusion technique",
      "Quantitative finance (investment appraisal, ratio analysis) covered with worked examples",
      "Strategic frameworks applied to real and past-paper business scenarios",
    ],
    format: "In Class & Online · Pakistan",
  },
  economics: {
    slug: "economics",
    name: "Economics",
    code: "9708",
    syllabusCode: "9708",
    overview:
      "Forte's A Level Economics course builds the analytical rigour Cambridge 9708 demands. From microeconomic theory of the firm through to macroeconomic policy debates, sessions teach students to construct diagrammatic and written arguments that earn marks at every level — from data response through to extended essay questions.",
    topics: [
      "Markets & the Price Mechanism — Supply, Demand & Equilibrium",
      "Elasticity — PED, PES, YED & Applications",
      "Government Intervention — Taxes, Subsidies & Price Controls",
      "Market Failure — Externalities, Public Goods & Information",
      "Theory of the Firm — Costs, Revenue & Market Structures",
      "Labour Markets & Wage Determination",
      "Macroeconomic Indicators — National Income, GDP & HDI",
      "Economic Growth, Development & Sustainability",
      "Monetary, Fiscal & Supply-Side Policy",
      "International Trade — Comparative Advantage & Protectionism",
      "Balance of Payments & Exchange Rate Systems",
    ],
    highlights: [
      "Economic diagrams drawn and annotated to the standard Cambridge expects",
      "Extended essay technique taught with a structured approach to each question type",
      "Both data response and essay papers practised consistently",
    ],
    format: "In Class & Online · Pakistan",
  },
  accounting: {
    slug: "accounting",
    name: "Accounting",
    code: "9706",
    syllabusCode: "9706",
    overview:
      "A Level Accounting at Forte covers the full Cambridge 9706 syllabus — from financial statements and partnership accounts through to management accounting and investment appraisal. Sessions develop both technical accuracy and the interpretive skill needed for the higher-order questions that separate A* students from the rest.",
    topics: [
      "Financial Accounting — Double Entry, Ledgers & Trial Balance",
      "Financial Statements — Income Statement & Balance Sheet",
      "Company Accounts — Published Accounts & IAS Standards",
      "Partnership Accounts",
      "Management Accounting — Absorption & Marginal Costing",
      "Cost-Volume-Profit Analysis",
      "Budgeting & Variance Analysis",
      "Investment Appraisal — Payback, ARR, NPV & IRR",
      "Cash Flow Forecasting",
      "Ratio Analysis & Interpretation",
      "Auditing Principles & Internal Controls",
    ],
    highlights: [
      "Financial and management accounting both taught to examination depth",
      "Investment appraisal methods explained clearly — the most tested higher-mark topic",
      "Ratio analysis and interpretation developed as an analytical skill, not memory work",
    ],
    format: "In Class & Online · Pakistan",
  },
  english: {
    slug: "english",
    name: "English Language",
    code: "9093",
    syllabusCode: "9093",
    overview:
      "A Level English Language at Forte develops the reading, analysis and writing skills Cambridge 9093 demands across all three papers. From writer's craft analysis to extended argumentative writing, every session builds the precision and voice that distinguishes A Level English at the top mark band.",
    topics: [
      "Reading & Comprehension — Explicit, Implicit & Inferential",
      "Writer's Effect & Language Analysis",
      "Directed Writing — Reports, Articles, Speeches & Letters",
      "Argumentative & Persuasive Writing",
      "Informative & Descriptive Writing",
      "Style, Tone, Audience & Purpose",
      "Summary & Note-Making",
      "Text Comparison & Evaluation",
      "Extended Writing — Planning & Developing a Sustained Argument",
      "Exam Technique for Paper 1, 2 & 3",
    ],
    highlights: [
      "Language analysis taught as a skill — specific techniques for identifying and commenting on effect",
      "All three Cambridge papers practised with structured approaches",
      "Extended writing developed over multiple sessions — argument, voice and structure",
    ],
    format: "In Class & Online · Pakistan",
  },
  psychology: {
    slug: "psychology",
    name: "Psychology",
    code: "9698",
    syllabusCode: "9698",
    overview:
      "A Level Psychology at Forte covers the full Cambridge 9698 syllabus — approaches, research methods and applied psychology — with a focus on the critical evaluation and evidence-based argumentation that earns marks at A Level. Sessions build both content knowledge and the analytical writing skill Cambridge's mark scheme rewards.",
    topics: [
      "Research Methods — Experiments, Surveys, Observations & Ethics",
      "Biological Approach — Brain Structure, Genes & Hormones",
      "Cognitive Approach — Memory, Perception & Schema Theory",
      "Developmental Psychology — Attachment, Piaget & Vygotsky",
      "Social Psychology — Conformity, Obedience & Prejudice",
      "Abnormal Psychology — Definitions, Classification & DSM",
      "Clinical Psychology — Case Studies & Treatments",
      "Applied Psychology — Criminal, Sport & Organisational",
      "Evaluating Research — Reliability, Validity & Ethics",
      "Statistical Analysis & Data Interpretation",
    ],
    highlights: [
      "Evaluation taught as a structured skill — not just 'strength/weakness' checklists",
      "Research methods fully covered — consistently the highest-mark topic in the exam",
      "Applied psychology options covered for Paper 3",
    ],
    format: "In Class & Online · Pakistan",
  },
  sociology: {
    slug: "sociology",
    name: "Sociology",
    code: "9699",
    syllabusCode: "9699",
    overview:
      "A Level Sociology at Forte develops the theoretical literacy and essay craftsmanship Cambridge 9699 demands. From structural theories to postmodern critiques, students learn to construct arguments that deploy theoretical perspectives as analytical tools — the skill that puts answers in the top mark band.",
    topics: [
      "Sociological Theory — Functionalism, Marxism, Feminism & Interactionism",
      "Research Methods — Design, Ethics & Data Interpretation",
      "Culture, Identity & Socialisation",
      "Social Inequality — Class, Gender, Ethnicity & Age",
      "The Family — Change, Diversity & Ideological Function",
      "Education — Achievement, Inequality & Policy",
      "Religion — Role, Secularisation & Fundamentalism",
      "Crime & Deviance — Theories, Statistics & Criminal Justice",
      "Media — Ownership, Representation & Audience",
      "Globalisation & International Development",
    ],
    highlights: [
      "Theoretical perspectives applied as analytical tools, not background knowledge",
      "Essay structure that deploys theory, evidence and evaluation in every paragraph",
      "Research methods covered rigorously — a consistent mark source students underestimate",
    ],
    format: "In Class & Online · Pakistan",
  },
};

export function getSubjectDetail(level: Level, slug: string): SubjectDetail | null {
  const map = level === "o-level" ? oLevelDetails : aLevelDetails;
  return map[slug] ?? null;
}
